### ISSUE TITLE
Search on 2 "other properties" seems to be allowed but doesn't work

### ISSUE THREAD

**Issue by Offirmo** [Codepoints/Codepoints.net#108]
The UI seems to imply it's possible:

![Screen Shot 2020-05-29 at 02 25 26](https://user-images.githubusercontent.com/603503/83167734-d409f000-a153-11ea-8dc7-1370c647cd8a.png)

when triggering the search, the 2 criterions are reflected in the url: https://codepoints.net/search?IDC=1&Dia=0 (cleaned)

However they don't appear in the UI anymore and the search size is unchanged. Doesn't seem to really work.

**Comment by Boldewyn** [comment]
Good catch, thank you! I’ll take a look as soon as I have finished the import work.

**Comment by Boldewyn** [comment]
![Screenshot_20221226_235827](https://user-images.githubusercontent.com/48738/209587488-eb7633d6-b511-4dec-8875-51f2143d49f3.png)
Works now. When I follow the link the appropriate widgets are set.
