### ISSUE TITLE
some characters don't render on some parts of the site

### ISSUE THREAD

**Issue by ashleedawg** [Codepoints/Codepoints.net#110]
Some characters (example U+1F916 🤖) don't render (for example, displaying ![image](https://user-images.githubusercontent.com/29980309/89526234-49b9ba00-d79c-11ea-9b21-d8b757015daf.png)) -- only on certain parts of the site.

So, a search for `robot` returns a list including the correct character -- except it's unrecognizable.  (See screenshot)

![image](https://user-images.githubusercontent.com/29980309/89526399-8980a180-d79c-11ea-9103-34e8b302e49c.png) ![image](https://user-images.githubusercontent.com/29980309/89526416-900f1900-d79c-11ea-828b-8bc2024fce9b.png)

(Windows 10, on both Firefox 79 and Chrome 83)

**Comment by Boldewyn** [comment]
Thank you for the notice! Yes, that’s due to platforms/browsers replacing emojis in some contexts. I have a rough idea how to fix that, but need to complete the import work first.

**Comment by Boldewyn** [comment]
Fixed in the new layout. We use Noto (and in this case specifically Noto Emoji) now consistently for all cp representations.
