### ISSUE TITLE
What happens with the search function?

### ISSUE THREAD

**Issue by Wernfried** [Codepoints/Codepoints.net#114]
Your page is great, but somehow the search is broken. 
I was searching for a simple ```é``` (Latin Small Letter E with Acute) It returns 49 hits, but the straight U+00E9 is not found!

Any plans to fix it?

Kind Regards
Wernfried

**Comment by Boldewyn** [comment]
Hi! Thanks for the report! Yes, I agree that should work differently. I’ll take a look.

There was some code in place to detect single code point searches. It’s well possible that that code went missing, when I switched the search engine technology.

**Comment by Boldewyn** [comment]
Fixed but not deployed yet. Single-character searches will now redirect to that character’s page.
