### ISSUE TITLE
Search provides incorrect result 

### ISSUE THREAD

**Issue by Sciencentistguy** [Codepoints/Codepoints.net#115]
When I entered "？" `U+FF1F FULLWIDTH QUESTION MARK` into the search bar, the only result is "𪳤" `U+2ACE4 CJK UNIFIED IDEO­GRAPH-​2ACE4`. Manually navigating to https://codepoints.net/U+FF1F works fine, so the page does exist.

Screenshot:

![image](https://user-images.githubusercontent.com/4983935/213798756-7a7efaaa-01f2-4a40-9e8a-6f2dcced6c62.png)

**Comment by Boldewyn** [comment]
Good catch, thank you! Yes, that is indeed strange. It should notice, that a single code point was searched and redirect to that specific one. I’ll investigate.

**Comment by Boldewyn** [comment]
Works now. A search for “？” redirects directly to the detail page for U+FF1F.

Thank you again for the report!

**Comment by Sciencentistguy** [comment]
No worries! Thanks for the speedy fix 🙂
