### ISSUE TITLE
Please update URLs

### ISSUE THREAD

**Issue by jsbien** [Codepoints/Codepoints.net#132]
Please update the URLs as the KLF digital library no longer exists:

The Polish translation is kindly provided by Janusz S. Bień, utilizing the terminology introduced in his paper [“Standard Unicode 4.0. Wybrane pojęcia i terminy”](https://www.researchgate.net/publication/37686764) and [subsequent publications](https://www.zotero.org/jsbien).

**Comment by Boldewyn** [comment]
Thank you for the notification! I’ll do the update with the next deployment.

**Comment by Boldewyn** [comment]
Completed.
