### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by Boldewyn** [Codepoints/Codepoints.net#16]
This is important, since sites with HTTPS cannot use the embed feature. FF22 also will cut support for HTTP in HTTPS context.

**Comment by mathiasbynens** [comment]
One of the things still triggering mixed content is http://piwik.manuel-strehl.de/piwik.js.

**Comment by mathiasbynens** [comment]
Ah, that’s the tracker you were talking about, of course.

**Comment by Boldewyn** [comment]
Yes, that's the only problem left. I wanted to take this as opportunity to move the tracker to the codepoints.net hoster, but had no time to tackle that. (I'll prioritize that, but it might still last a bit.)

Where the tracker is at the moment, it's a huge problem to simply switch to SSL. Shared hoster, additional IP address 1€ a month, ... in a nutshell, not feasible.

**Comment by mathiasbynens** [comment]
No need for additional IP addresses — you could just use SNI. (I do it, too!)

**Comment by Boldewyn** [comment]
That's how the codepoints.net hoster does it, and it's a joy to work this way. Unfortunately, the piwik.manuel-strehl.de hoster doesn't support that. (There would be an option using non-default ports and self-signed certs, but that's replacing one evil with another.)

**Comment by Boldewyn** [comment]
On the plus side: The API works over HTTPS, too, and there is no mixed-content warning :-)

**Comment by Boldewyn** [comment]
Closer: Tracker runs at stats.codepoints.net, now. Just waiting for the SSl cert to make it to the server config, then I'll switch.

**Comment by Boldewyn** [comment]
Fixed. The tracker is now ported, and no mixed-content warning is thrown.

**Comment by mathiasbynens** [comment]
:+1: 

Now please enable HSTS as well!

**Comment by mathiasbynens** [comment]
Example code for Apache: https://github.com/h5bp/server-configs-apache/blob/08e7a87a0ac54502a21b570be700a7af1ad2ecae/dist/.htaccess#L575-L599

**Comment by mathiasbynens** [comment]
Then you can also submit to http://hstspreload.appspot.com/

**Comment by Boldewyn** [comment]
Done. Thanks for pointing me to that! (I thought of this list, too, but couldn't recall how that header was called.)

It might be, that the preload request is denied, because I do not force redirection to HTTPS. This is, for now, by choice, until I am confident, that there are no hidden problems (like API consumption via HTTPS). When I will start forcing redirection, I'll also re-submit to the preload list then.
