### ISSUE TITLE
Search should give absolute priority to exact name and decomposition matches

### ISSUE THREAD

**Issue by Hexstream** [Codepoints/Codepoints.net#25]
Searching for `tm` should land directly on the `TRADE MARK SIGN` page, not display 451 results.
This is an exact match on the decomposition information.

(*And at the risk of being overly explicit:*)
Searching for `trade mark sign` should land directly on the `TRADE MARK SIGN` page, not display 4025 results.
Need I say it? This is an exact match on the name. ;)

**Comment by Boldewyn** [comment]
Fixed: a44b853cba3de6bb8b1d9c72ac627e8ad3c8d231
