### ISSUE TITLE
Search for UTF-8

### ISSUE THREAD

**Issue by sebgymn** [Codepoints/Codepoints.net#29]
Hello, I have been unable to find a character from its UTF-8 value. For example, I searched c3a7, which translates to different characters in UTF-8 and UTF-16, but I couldn't find the UTF-8 one using the site. Maybe there should be extra query type for it in extended search section.

**Comment by Boldewyn** [comment]
Fixed (in a way): The search now understands and interprets URL encoded strings: `https://codepoints.net/search?q=%25C3%25BC` (search term: `%C3%BC`) yields the page of `ü`.
