### ISSUE TITLE
Incorrect data for 'noncharacter' property

### ISSUE THREAD

**Issue by grantm** [Codepoints/Codepoints.net#46]
On [this page](https://codepoints.net/U+10FFFF), the 'Noncharacter Code Point (NChar)' property is displayed with a red X.

I believe this is incorrect since the Unicode Character Database defines this codepoint (and the preceding one) as:

    <noncharacter first-cp="10FFFE" last-cp="10FFFF" gc="Cn" bc="BN" ea="N" NChar="Y"/>

Also, when I try to access the character details via the [REST API]( https://codepoints.net/api/v1/codepoint/10FFFF) I get this response:

    {"problemType":"https:\/\/codepoints.net\/api\/v1\/problem\/not_found","title":"Not a codepoint"}

Thanks for building this awesome resource.  I'm already linking to it and intend to make use of the REST API from my [Unicode Character Finder](http://www.mclean.net.nz/ucf/) app.

**Comment by Boldewyn** [comment]
Yes, indeed. It seems, U+EFFFE, U+EFFFF, U+FFFFE, U+FFFFF, U+10FFFE and U+10FFFF are handled specially, similar to U+FFFE and U+FFFF.

I'll see to it, that those get incorporated. That should also fix the API's response.

When you use the API, would you want to have Private Use codepoints also returning a 200 response? At the moment they are handled as "does not exist", but in a way they are defined codepoints.

**Comment by grantm** [comment]
From my application it doesn't matter because I already know if a codepoint is in a PUA so there's not really any point querying for more detailed information.

**Comment by Boldewyn** [comment]
OK, we're missing _all_ noncharacters. This is an oversight in the way https://github.com/Boldewyn/unicodeinfo parses the XML file. ([Unicode's FAQ on nonchars](http://www.unicode.org/faq/private_use.html#nonchar1))

**Comment by Boldewyn** [comment]
I'm almost finished. However, some of the nonchars have no block associated. That breaks an, in hindsight, naïve assumption of mine, which I need to fix first.

**Comment by Boldewyn** [comment]
Fixed: https://codepoints.net/U+6FFFF
