### ISSUE TITLE
Update to Unicode 8.0.0

### ISSUE THREAD

**Issue by Boldewyn** [Codepoints/Codepoints.net#48]
* [x] unicodeinfo is updated
* [x] look into how to update the db
* [x] add changes to code, e.g. class `UnicodeInfo`
* [x] update fonts and previews

**Comment by mathiasbynens** [comment]
Shouldn’t we wait until Unicode v8.0.0 is officially released? (Planned for August 26, 2015.)

**Comment by Boldewyn** [comment]
In principle I agree, that basing on a beta standard is a bad idea. But from that page:

> The Unicode Character Database, Code Charts, and Annexes for Version 8.0 were released on June 17, 2015.

If the database is stable, I'd vote for adding it. That's the authoritative source for the site, anyway. The copy of the reports is usually only of informative interest (and the [draft](http://www.unicode.org/reports/tr44/tr44-15.html) seems to be quite stable already).

Anyways, it's unlikely that I complete the update before the weekend. So, plenty of time to think this through :)

**Comment by mathiasbynens** [comment]
> The Unicode Character Database, Code Charts, and Annexes for Version 8.0 were released on June 17, 2015.

That page is a draft; it just shows the current date, every day, until it gets published.

**Comment by Boldewyn** [comment]
OK, that's a bad idea from the one updating that page. Thanks!

(I've got the idea from that being the correct date from this post: http://blog.unicode.org/2015/03/unicode-80-beta-review.html: "...scheduled for June 2015...")

**Comment by mathiasbynens** [comment]
Never mind – Unicode v8.0.0 has just been officially released! http://unicode.org/versions/Unicode8.0.0/

**Comment by Boldewyn** [comment]
Update (almost) complete. Missing but deferred: Updating some fonts, like Noto or Symbola.
