### ISSUE TITLE
Add a "copy to clipboard" feature

### ISSUE THREAD

**Issue by Boldewyn** [Codepoints/Codepoints.net#53]
This issue is here to track progress. The work is already under way.

Problem: Flash sucks and the Clipboard API is not yet up to speed.

Also, the feature will most likely be combined with a more generic "scratchpad" to collect several codepoints at once.

**Comment by mathiasbynens** [comment]
FWIW, Opera 30 and Chrome 43 support programmatic cut/copy to clipboard: https://dev.opera.com/blog/opera-30/#javascript-powered-copycut-functionality

**Comment by Boldewyn** [comment]
Firefox 41: https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/ (via @​rauschma)
