### ISSUE TITLE
Cloudflare bans access for command-line HTTPS clients

### ISSUE THREAD

**Issue by daxim** [Codepoints/Codepoints.net#57]
What's this discrimination good for? `curl` for example is not affected.

    $ GET 'https://codepoints.net/api/v1/codepoint/0078?property=na&callback=foo' | ack ban
                <p>The owner of this website (codepoints.net) has banned your access based on your browser's signature (21c741c402dc0a2a-ua24).</p>
    $ GET -v
    This is lwp-request version 6.09 (libwww-perl-6.13)

    Copyright 1995-1999, Gisle Aas.

    This program is free software; you can redistribute it and/or
    modify it under the same terms as Perl itself.

**Comment by Boldewyn** [comment]
I haven't configured CloudFlare for any specific filtering. This is unfortunate. I only hope, that it doesn't come as "feature" of their free plan.

Until I have figured that out, you could try Mashape's mirror of the API: https://www.mashape.com/boldewyn/unicode-codepoints

**Comment by Boldewyn** [comment]
I've loosened the CloudFlare settings for `/api/v1/*`. Would you mind testing, if the problem persists?

**Comment by daxim** [comment]
Confirmed works
