### ISSUE TITLE
server returns status 500

### ISSUE THREAD

**Issue by daxim** [Codepoints/Codepoints.net#58]
$ curl -v 'https://codepoints.net/api/v1/codepoint/0078?property=na&callback=foo'
    […]
    < HTTP/1.1 500 Internal Server Error
    < Server: cloudflare-nginx

Can also be observed in Firefox on forced reload.

**Comment by Boldewyn** [comment]
Hm. I don't see that. But that doesn't mean a thing, since the site is behind CloudFlare, and who knows, what is cached right now? Thanks for reporting, I'll investigate further.

**Comment by daxim** [comment]
Some software versions, if it matters:

    $ curl --version
    curl 7.42.1 (x86_64-suse-linux-gnu) libcurl/7.42.1 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.31 libssh2/1.5.0
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
    Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink

    $ cat /etc/os-release
    NAME=openSUSE
    VERSION="13.2 (Harlequin)"
    VERSION_ID="13.2"
    PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
    ID=opensuse
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:opensuse:opensuse:13.2"
    BUG_REPORT_URL="https://bugs.opensuse.org"
    HOME_URL="https://opensuse.org/"
    ID_LIKE="suse"

    $ zypper info MozillaFirefox
    Repository: repo-update
    Name: MozillaFirefox
    Version: 40.0-38.1
    Arch: x86_64
    Vendor: openSUSE
    Installed: Yes
    Status: up-to-date
    Installed Size: 92.6 MiB
    Summary: Mozilla Firefox Web Browser
    Description:
      Mozilla Firefox is a standalone web browser, designed for standards
      compliance and performance.  Its functionality can be enhanced via a
      plethora of extensions.

**Comment by Boldewyn** [comment]
OK, I can see that now, too. Will investigate deeper.

**Comment by Boldewyn** [comment]
Uh oh. There was indeed a 500-producing bit in my code. This should be fixed now. Thanks for reporting!
