### ISSUE TITLE
Become an oEmbed provider

### ISSUE THREAD

**Issue by Boldewyn** [Codepoints/Codepoints.net#62]
Read the info at http://oembed.com/, implement an API endpoint and submit the data to https://github.com/iamcal/oembed/tree/master/providers.yml. Result: If someone pastes

    https://codepoints.net/U+1234

or

    https://codepoints.net/☺

in a WordPress post, WordPress should automatically convert the URL to our [embedded iframe](https://blog.codepoints.net/embed-codepoints-on-your-website.html).

**Comment by johnbillion** [comment]
:+1: 

Just a note to say that automatic support in WordPress will only work in the upcoming WordPress 4.4 release (due out in the next couple of weeks), and as long as the URL has autodiscovery headers in place. WordPress versions prior to that use a whitelist of trusted providers.

**Comment by Boldewyn** [comment]
Good to know, thanks!

For reference: Since WP will be the largest oEmbed consumer out of the box, we should make sure to get it right there. Articles:

https://codex.wordpress.org/Embeds
https://make.wordpress.org/core/2015/10/28/new-embeds-feature-in-wordpress-4-4/

**Comment by Boldewyn** [comment]
Presumably fixed in 641771b72303eb9097193bbf0aeaabfc9616d4c4, but not yet tested with Wordpress yet. I'll close the ticket, when I've seen it working once.

**Comment by Boldewyn** [comment]
Yep, Wordpress 4.4 works as intended. 🍾

**Comment by johnbillion** [comment]
Which URL are you using to test the embed? Testing with `https://codepoints.net/☺` and `https://codepoints.net/U+0055` and neither of them embed for me.

(I'm one of the maintainers of the embeds components in WordPress by the way. Interested to find out where this works and where it doesn't.)

**Comment by Boldewyn** [comment]
I tried both variants with a WP 4.4 RC1 some time ago. There it worked like a charm. Both URL forms (the one getting redirected to the other) include the appropriate `<link type="application/json+oembed">` for auto-detection.
