### ISSUE TITLE
Searching for "PLUS" don't retrieve the PLUS SIGN (U+002B)

### ISSUE THREAD

**Issue by Pigeo** [Codepoints/Codepoints.net#70]
When searching for "PLUS" (from codepoints.net homepage), the search results do not contain the PLUS SIGN (U+002B) whereas it should.

**Comment by Boldewyn** [comment]
Thanks for the report! I tried the search, and U+002B is there, but fairly defeated in 23rd place. I agree, that this is not a very intuitive result.

All previously found code points have the string "PLUS" more than once in their name and are hence weighted higher. (U+00B1 is a special case. It has a "Unicode 1" name, that is also weighted high.) So _in principle_, the results are alright. In practice it's of course needlessly surprising.

Would it work for you, if you could **sort the matches by code point value** ascending from the search form? In this specific case there would still be some matches before the PLUS character. (That's b/c, not doing full natural language processing here, the code reduces "plus" to an assumed singular "plu" and match against `/plu.*/`, matching the string "plural" in some Wikipedia excerpts.) But it might be easier to spot the result then.

Another fix would be to add specific weight to **characters starting with the requested string**. But I'm not sure, if that wouldn't produce other unwanted side effects (like presenting U+1F4A8 DASH SYMBOL, 💨, before the em and en dashes).

**Comment by Pigeo** [comment]
Hello,
    
    thanks for the reply.
    
    I think sorting the matches by code point value ascending is a good
    option.
    
    (in this particular case, I knew what I was searching for and I knew
    it was in the basic latin block)
    
    Best regards,
    
    Pierre-Aurélien Georges
    
    
    Le 06/01/2016 20:09, Manuel Strehl a
      écrit :
    
    
      Thanks for the report! I tried the search, and U+002B is there,
        but fairly defeated in 23rd place. I agree, that this is not a
        very intuitive result.
      All previously found code points have the string "PLUS" more
        than once in their name and are hence weighted higher. (U+00B1
        is a special case. It has a "Unicode 1" name, that is also
        weighted high.) So in principle, the results are
        alright. In practice it's of course needlessly surprising.
      Would it work for you, if you could sort the matches
          by code point value ascending from the search form?
        In this specific case there would still be some matches before
        the PLUS character. (That's b/c, not doing full natural language
        processing here, the code reduces "plus" to an assumed singular
        "plu" and match against /plu.*/, matching the
        string "plural" in some Wikipedia excerpts.) But it might be
        easier to spot the result then.
      Another fix would be to add specific weight to characters
          starting with the requested string. But I'm not sure,
        if that wouldn't produce other unwanted side effects (like
        presenting U+1F4A8 DASH SYMBOL, 💨,
        before the em and en dashes).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Boldewyn** [comment]
The new full-text search engine fixed this problem for us: https://codepoints.net/search?q=PLUS now shows U+002B as the very first result.
