### ISSUE TITLE
Integrate emoji_data.txt properties

### ISSUE THREAD

**Issue by drott** [Codepoints/Codepoints.net#71]
It would be great to have the additional properties from http://www.unicode.org/Public/emoji/2.0/emoji-data.txt integrated into the character properties table at the bottom.

**Comment by Boldewyn** [comment]
Thanks for the report! That's also partly related to #66 and #49.

When I address this, the information should also be added to the search index table. So, e.g., when someone searches "emoji", the characters are found.

**Comment by Boldewyn** [comment]
Fixed in 1cd80114fd000ce5e662a940f0c5e2a775f68599 and live since end of November.

Thanks again for the report!
