### ISSUE TITLE
Typo (apparent copy/paste error) in U+FE0F page

### ISSUE THREAD

**Issue by jibal** [Codepoints/Codepoints.net#95]
https://codepoints.net/U+FE0F

> If that is a symbol, dingbat or emoji, U+FE0E forces it to be rendered as a colorful image as compared to a monochrome text variant.

"U+FE0E" should be "U+FE0F". (cf. the U+FE0E page)

**Comment by Boldewyn** [comment]
Fixed. Thanks for reporting! :smile:
