### ISSUE TITLE
Upgrade to Unicode v9

### ISSUE THREAD

**Issue by Boldewyn** [Codepoints/Codepoints.net#97]
_Sigh._ There goes my spare time...

**Comment by mathiasbynens** [comment]
Is upgrading not an automated process?

**Comment by Boldewyn** [comment]
Unfortunately not. I have to update [unicodeinfo](https://github.com/Codepoints/unicodeinfo/) to take into account new properties/values for existing properties. If that's done, most things are fetched automatically (i.e., Wikipedia posts), but still there'd be some manual tweaking involved, including uploading some MB to my hoster on a crappy uplink connection.

Then there are no images for the new characters (partly because I didn't get to finally test and add a Noto font -> SVG converter).

All in all I'd need ~1 day (more or less undisturbed) for the update, and, yes, I didn't have such a luxury since July...

**Comment by mathiasbynens** [comment]
unicodeinfo now has Unicode v9 support: https://github.com/Codepoints/unicodeinfo/commit/e827d1661d238d9fca8803319eb1959eecc68254

Let the automatic fetching commence? ;)

**Comment by Boldewyn** [comment]
Thanks! I'll try to kickstart the import on the weekend.

**Comment by shreevatsa** [comment]
Unicode 10.0.0 is just around the corner :-) http://www.unicode.org/versions/Unicode10.0.0/

**Comment by shreevatsa** [comment]
Unicode 10.0.0 has been released (http://blog.unicode.org/2017/06/announcing-unicode-standard-version-100.html). Any hope of an update? Maybe if you document the process, someone else can send a PR…

**Comment by Boldewyn** [comment]
I've worked to consolidate the data gathering, and put that work into [Codepoints/unicode2mysql](https://github.com/Codepoints/unicode2mysql). As of now, it's still a work in progress, but I'm confident, that I can get together a close-to-working version this week. The result should be a single SQL file that will replace all the data currently in the codepoints.net database.

The database is a read-only data source for the PHP code. So everything is collected and put into the DB before the first request is handled. That is especially true for two large-ish items, the images and the search index. The former are now created from the Noto font as SVG images. That will take a bit of work on the codepoints.net side, since PHP expects a base64 encoded PNG currently.

The search index is not yet handled. For that I need to adapt the `tools/create_search_index.py` tool. Should probably be straight-forward, but the devil is in the detail.

If anyone takes a look at unicode2mysql and wants to play with it, I'd be happy, if that would result in a PR to the README over there on how to get things running. Maybe this would really make it easier for contributors as soon as Unicode 11 is due.

Thank you for nagging me about getting this done! I really appreciate that.

**Comment by mathiasbynens** [comment]
Any luck generating the SQL file?

**Comment by Boldewyn** [comment]
I thought I was finished, when I noticed, that FontForge failed in converting the CJK and Symbols fonts to SVG. That was what I did the last two evenings, trying to convert them from OTF to SVG with no success. Actually, I currently out of ideas how to do so. Perhaps switching to another CJK font.

(The source problem is, that I want/need to switch from GNU Unifont PNGs to SVG paths extracted from fonts. I'm quite done with regular characters but need more work for combining marks, spaces, and CJK characters. And yes, it was a bad idea to couple that with the update script.)

**Comment by jsbien** [comment]
Hi!

I'm on the FontForge mailing list, I can forward your questions.

Best regards

Janusz

Quote/Cytat - Manuel Strehl <notifications@github.com> (Thu 13 Jul  
2017 10:07:42 AM CEST):

> I thought I was finished, when I noticed, that FontForge failed in  
> converting the CJK and Symbols fonts to SVG. That was what I did the  
> last two evenings, trying to convert them from OTF to SVG with no  
> success. Actually, I currently out of ideas how to do so. Perhaps  
> switching to another CJK font.
>
> (The source problem is, that I want/need to switch from GNU Unifont  
> PNGs to SVG paths extracted from fonts. I'm quite done with regular  
> characters but need more work for combining marks, spaces, and CJK  
> characters. And yes, it was a bad idea to couple that with the  
> update script.)
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Codepoints/Codepoints.net/issues/97#issuecomment-315004176



-- 
Prof. dr hab. Janusz S. Bień -  Uniwersytet Warszawski (Katedra  
Lingwistyki Formalnej)
Prof. Janusz S. Bień - University of Warsaw (Formal Linguistics Department)
jsbien@uw.edu.pl, jsbien@mimuw.edu.pl, http://fleksem.klf.uw.edu.pl/~jsbien/

**Comment by Boldewyn** [comment]
Thank you! I've opened a Github issue, https://github.com/fontforge/fontforge/issues/3115, since there is a Fontforge crash involved, which is a regression from the older stock version distributed with Ubuntu.

If it's adequate, you could point the people on the mailing list to that issue.

**Comment by jsbien** [comment]
The message from the FontForge list:

On Mon, Jul 17 2017 at 14:51 CEST, dave@lab6.com writes:
> I imagine this will never be fixed. 
>
> I recommend using inkscape and a python script to do it

-- 
                           ,   
Prof. dr hab. Janusz S. Bien -  Uniwersytet Warszawski (Katedra Lingwistyki Formalnej)
Prof. Janusz S. Bien - University of Warsaw (Formal Linguistics Department)
jsbien@uw.edu.pl, jsbien@mimuw.edu.pl, http://fleksem.klf.uw.edu.pl/~jsbien/

**Comment by Boldewyn** [comment]
Short update so far: Font formats are a f**king mess. That is basically the gist from what I unearthed and achieved the last week. I am truly astonished, how any piece of software is able to render _any_ glyph at all.

**Comment by mathiasbynens** [comment]
Hang in there, @Boldewyn!

**Comment by shreevatsa** [comment]
Unicode 11 was released today :-) http://unicode.org/versions/Unicode11.0.0/

This one (codepoints.net) is my favourite of all the “get info about a Unicode character” websites out there, and it's great that it's open-source… would love to see it up-to-date!

**Comment by gnprice** [comment]
Just wanted to add that this is the first "info about a Unicode codepoint" site I've found that I really like, and it's awesome that it's open-source too. It'd be even better with Unicode 9 :-), or even later.

Is it possible there might be a way to complete the update for the characters/glyphs/etc. that things do work for, and leave the others for another time?

**Comment by Serentty** [comment]
And now we're at Unicode 13. It's a shame because this site has way more features than the Compart Unicode browser, but I find myself unable to use it a lot of the time because so many characters are missing.

**Comment by Boldewyn** [comment]
Wel, well. It took me to Unicode 15, but finally I can close this ticket. About time, if I may say so. Thank you all for your patience!
