### ISSUE TITLE
Add new emoji names

### ISSUE THREAD

**Issue by mathiasbynens** [Codepoints/Codepoints.net#99]
Full emoji list: http://unicode.org/emoji/charts-beta/full-emoji-list.html

E.g. https://codepoints.net/U+1F922 is missing.

**Comment by drott** [comment]
:+1: https://codepoints.net/U+1F973 results in CECI N’EST PAS UNICODE

Thanks for looking into it.

**Comment by Boldewyn** [comment]
Will be fixed by #97 whenever I finally get that stuff merged back. But thanks for nagging me (seriously!).
